[colors]
background = "#020202"
foreground = "#d8e1e6"

black = "#030404"
red = "#fc62b1"
green = "#8aa54d"
yellow = "#faaa57"
blue = "#31c5ed"
magenta = "#c3a3e8"
cyan = "#2cc6a3"
white = "#dce4e8"

light-black = "#555f63"
light-red = "#fca8cd"
light-green = "#a8c55f"
light-yellow = "#ffc47b"
light-blue = "#69d7f4"
light-magenta = "#d8baf5"
light-cyan = "#5edbbf"
light-white = "#ffffff"

cursor = "#ffffff"
selection-background = "#212528"
selection-foreground = "#ffffff"

bar = "#020202"
tabs = "#78858c"
tabs-active = "#ffffff"
split = "#212528"

[fonts]
family = "Ioskeley Mono Term Medium"
size = 18
