[project]
name = "opencode"
revision = "1.0"

[providers]
proton = "protonpass://secretspec"

[profiles.default]
YNAB_API_KEY = { description = "YouNeedABudget personal API token", required = true, providers = [
  "proton",
] }
LINEAR_API_KEY = { description = "Livestorm Linear API token", required = true, providers = [
  "proton",
] }
